version: '3.8'

services:
  # Added for testing
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on: 
      - postgres
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
